version: "3.4"

services:
  mysqldb:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: movie
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - shared-net
    volumes:
      - ./mysql/data:/backup

  app:
    image: movieapi
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/movie?useSSL=false&allowPublicKeyRetrieval=true
      - SERVER_PORT=8080
    restart: always
    networks:
      - shared-net

  server:
    build:
      context: ./
      dockerfile: Dockerfile.server
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
    environment:
      - MYSQL_HOST=mysqldb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=movie
    networks:
      - shared-net

networks:
  shared-net:
    driver: bridge
